import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConsultationProvider } from "@/context/ConsultationContext";
import Navbar from "@/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[#0b0c10] text-[#f3f4f6] font-sans antialiased selection:bg-brand-gold selection:text-[#0b0c10]">
        <ConsultationProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow">{children}</main>
            {/* <Footer /> */}
          </div>
        </ConsultationProvider>
      </body>
    </html>
  );
}
