import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConsultationProvider } from "@/context/ConsultationContext";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-brand-dark text-[#f3f4f6] font-sans antialiased selection:bg-brand-gold selection:text-white">
        <ConsultationProvider>
          <div className="">
            <Navbar />
            <main className="flex-grow">
              {children}

              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                closeOnClick
                pauseOnHover
                draggable
                theme="light"
              />
            </main>
            <Footer />
          </div>
        </ConsultationProvider>
      </body>
    </html>
  );
}
